### ISSUE TITLE
随便写写

### ISSUE THREAD

**Issue by linxz** [linxz/CSS_Skills#1]
写什么好呢，文字这东西，我玩不来，就会一点CSS2，有兴趣的东西一起来写写CSS方面的小技巧吧，或者提点想法也好啊。

**Comment by Mingdy** [comment]
现在才发现能用得好css2的人才是真正的高手，所以，志哥好腻害！

**Comment by ideazhao** [comment]
说起小技巧，那个经典的“十字架”算不算？引无数英雄竞折腰啊~标准新加进去的东东层出不穷，还是有不少东西可玩儿的~

**Comment by linxz** [comment]
@linggan100 那个十字架我觉得应该不算是吧，个人觉得那个主要是考验一个人对知识的理解程度。

**Comment by Keystion** [comment]
字母A-Z css写这个算一个吧

**Comment by linxz** [comment]
@Keystion 算……十分滴算啊。

**Comment by ideazhao** [comment]
各种进度条来一个呗？

**Comment by linxz** [comment]
@linggan100 进度条这个东西，网络上不是有很多么，还有有现成的制作工具啊……

**Comment by ideazhao** [comment]
那还有什么没有。。。别人的是别人的，志哥牌儿——我们值得拥有！~

**Comment by lijuns** [comment]
别人的是别人的，志哥牌儿——我们值得拥有！~
